/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 84866
 */

// IMPORT THƯ VIỆN
import Exception_and_StoreSenSor.Heght_Exception;
import Exception_and_StoreSenSor.Nulll_Exception;
import Exception_and_StoreSenSor.Radius_Exception;
import Exception_and_StoreSenSor.Width_Exception;
import Exception_and_StoreSenSor.Width_Less_Height;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Input_JFrame_Closed_Belt_Region extends javax.swing.JFrame {

    /**
     * Creates new form FormClose_Region
     */
    public Input_JFrame_Closed_Belt_Region() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdai = new javax.swing.JTextField();
        txtrong = new javax.swing.JTextField();
        txtbk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Kiểm tra ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Vẽ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Nhập dữ liệu");

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nhập chiều dài");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nhập chiều rộng");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Nhập bán kính");

        txtdai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdaiKeyTyped(evt);
            }
        });

        txtrong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtrong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrongKeyTyped(evt);
            }
        });

        txtbk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtbk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbkKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtrong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbk, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(txtdai, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtdai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cauhinh = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            //KIỂM TRA NGOẠI LỆ
            checkException();
            checkDai(Integer.parseInt(txtdai.getText().trim()));
            checkRong(Integer.parseInt(txtrong.getText().trim()));
            checkRadius(Integer.parseInt(txtbk.getText().trim()));
            checkWidthandHight(Integer.parseInt(txtdai.getText().trim()), Integer.parseInt(txtrong.getText().trim()));
            
            //BIẾN XEM NGƯỜI DÙNG DÃ KIỂM TRA HAY CHƯA
            cauhinh = 1;
            JOptionPane.showMessageDialog(rootPane, "Dữ liệu hợp lệ");
        } catch (Nulll_Exception ex) {
            
            
            //CÁC LỚP THÔNG BÁO KHI NGOẠI LỆ XẢY RA
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (Width_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (Heght_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (Radius_Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (Width_Less_Height ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private void checkException() throws Nulll_Exception {
        
        //NGOẠI LỆ CHECK NULL
        if (txtdai.getText().trim().equals("")) {
            throw new Nulll_Exception("Chiều dài trống. Vui lòng thử lại!!");
        }
        if (txtbk.getText().trim().equals("")) {
            throw new Nulll_Exception("Bán kính trống. Vui lòng thử lại!!!");
        }
        if (txtrong.getText().trim().equals("")) {
            throw new Nulll_Exception("Chiều rộng trống. Vui lòng thử lại!!!");
        }

    }

    private void checkWidthandHight(int x, int y) throws Width_Less_Height {
        if (x < y) {
            //NGOẠI LỆ CHECK DÀI NHỎ HƠN RỘNG
            throw new Width_Less_Height("Chiều dài phải lớn hơn chiều rộng");
        }
    }

    private void checkDai(int x) throws Width_Exception {
        if (x < 200 || x > 600) {
            //NGOẠI LỆ CHECK DÀI
            throw new Width_Exception("Chiều dài nằm trong khoảng từ 200 đến 600");
        }
    }

    private void checkRong(int x) throws Heght_Exception {
        if (x < 200 || x > 400) {
            //NGOẠI LỆ CHECK RỘNG
            throw new Heght_Exception("Chiều rộng nằm trong khoảng từ 200 đến 400");
        }
    }

    private void checkRadius(int x) throws Radius_Exception {
        if (x < 45 || x > 70) {
            
            //NGOẠI LỆ CHECK BÁN KÍNH
            throw new Radius_Exception("Bán kính nằm trong khoảng từ 45 đến 70");
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //DÓNG JFRAME
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (cauhinh == 0) {
            
            //TRƯỜNG HỢP CHƯA KIỂM TRA DỮ LIỆU
            JOptionPane.showMessageDialog(rootPane, "Vui lòng kiểm tra dữ liệu trước khi vẽ");
        } else {
            //GẮN GIÁ TRỊ
            int dai = Integer.parseInt(txtdai.getText());
            int rong = Integer.parseInt(txtrong.getText());
            int bankinh = Integer.parseInt(txtbk.getText());
            //TRUYỀN GIÁ TRỊ
            JFrame MainFrame = new JFrame();
            MainFrame.setSize(dai + 400, rong + 400);
            
            //GỌI JPANEL
            Draw_A_Closed_Belt_Region Closed_RegionPanel = new Draw_A_Closed_Belt_Region(dai, rong, bankinh);
            MainFrame.add(Closed_RegionPanel);
            //SET TITLE
            MainFrame.setTitle("A closed belt region");
            MainFrame.setLocationRelativeTo(null);
            MainFrame.setVisible(true);
            cauhinh = 0;
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //PHÍM CLEAR
        txtbk.setText("");
        txtdai.setText("");
        txtrong.setText("");
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtdaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaiKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtdaiKeyPressed

    private void txtdaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaiKeyTyped
        // TODO add your handling code here:
        //KHÔNG CHO NHẬP KÍ TỰ CHỮ
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdaiKeyTyped

    private void txtrongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrongKeyTyped
        // TODO add your handling code here:
        //KHÔNG CHO NHẬP KÍ TỰ CHỮ
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtrongKeyTyped

    private void txtbkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbkKeyTyped
        // TODO add your handling code here:
        //KHÔNG CHO NHẬP KÍ TỰ CHỮ
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtbkKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_JFrame_Closed_Belt_Region.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_JFrame_Closed_Belt_Region.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_JFrame_Closed_Belt_Region.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_JFrame_Closed_Belt_Region.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_JFrame_Closed_Belt_Region().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtbk;
    private javax.swing.JTextField txtdai;
    private javax.swing.JTextField txtrong;
    // End of variables declaration//GEN-END:variables
}
